AY1920S1-CS2113-T14-1/main

build.gradle
src/main/java/duke/Duke.java
src/main/java/duke/command/NewReminderCommand.java
src/main/java/duke/task/Reminder.java
src/main/java/duke/task/TaskList.java
src/test/java/ReminderTest.java
src/test/java/TaskListTest.java

Minor cleanup, and packaged Jar for release!

[CS2113T-W12-1]-aquohn-A-Jar

---

src/test/java/CommandTest.java
src/test/java/NewRecurringTaskCommandTest.java
src/test/java/ParserTest.java
src/test/java/SnoozeCommandTest.java
src/test/java/TaskListTest.java

Add SnoozeCommandTest and abstract out CommandTest

---

src/main/java/duke/command/NewDoWithinPeriodCommand.java
src/main/java/duke/command/NewFixedDurationCommand.java
src/main/java/duke/task/EventTask.java
src/main/java/duke/task/FixedDurationTask.java
src/main/java/duke/task/TimedTask.java
src/main/java/duke/task/Tsk.java
src/test/java/DurationPeriodTest.java
src/test/java/ParserTest.java
src/test/java/SnoozeCommandTest.java
src/test/java/TaskListTest.java
src/test/java/TaskTest.java

Provide support for FixedDurationTasks and DoWithinPeriodTasks.
Modified Event tasks to have a start and end time

B-FixedDurationTasks and B-DoWithinPeriodTasks

---

src/main/java/duke/command/ArgCommand.java
src/main/java/duke/command/Command.java
src/main/java/duke/command/MultiArgCommand.java
src/main/java/duke/command/NewEventCommand.java
src/main/java/duke/command/NewFixedDurationCommand.java
src/main/java/duke/command/NewTimedTaskCommand.java
src/main/java/duke/command/Ui.java
src/main/java/duke/gui/Message.java
src/main/java/duke/task/Task.java
src/main/java/duke/task/TaskList.java
src/main/java/duke/task/TimedTask.java
src/test/java/CommandTest.java
src/test/java/NewRecurringTaskCommandTest.java
src/test/java/NewReminderCommandTest.java
src/test/java/ReminderTest.java
src/test/java/TaskListTest.java

Enhancements include:
1. Removing unused imports
2. Using explicit scoping

Make code style enhancements

---

docs/UserGuide.adoc

Final update of UserGuide for Milestone v1.1

---

src/main/java/duke/Duke.java
src/main/java/duke/DukeCore.java
src/main/java/duke/command/ArgCommand.java
src/main/java/duke/command/ByeCommand.java
src/main/java/duke/command/Command.java
src/main/java/duke/command/DeleteCommand.java
src/main/java/duke/command/DoneCommand.java
src/main/java/duke/command/FindCommand.java
src/main/java/duke/command/ListCommand.java
src/main/java/duke/command/NewDeadlineCommand.java
src/main/java/duke/command/NewDoWithinPeriodCommand.java
src/main/java/duke/command/NewEventCommand.java
src/main/java/duke/command/NewFixedDurationCommand.java
src/main/java/duke/command/NewRecurringTaskCommand.java
src/main/java/duke/command/NewReminderCommand.java
src/main/java/duke/command/NewToDoCommand.java
src/main/java/duke/command/SnoozeCommand.java
src/main/java/duke/command/ViewCommand.java
src/test/java/CommandTest.java
src/test/java/NewRecurringTaskCommandTest.java
src/test/java/SnoozeCommandTest.java

Contexts, Dr. Duke, refer to different screens. The DukeContext class, which held the core objects used in Duke, will now be renamed DukeCore to prevent confusion.

Replace DukeContext with DukeCore

---

.travis.yml
build.gradle

Add Coveralls

---

src/main/java/duke/task/DukeData.java
src/main/java/duke/task/DukeObject.java
src/main/java/duke/task/Evidence.java
src/main/java/duke/task/Impression.java
src/main/java/duke/task/Patient.java
src/main/java/duke/task/Treatment.java

Created initial DukeObjects.
Todo: toString methods, discharge method

Created initial duke objects

---

src/main/java/duke/task/Observation.java
src/main/java/duke/task/Result.java

Created initial Result and Observation objects.
Todo: toString methods
This closes #91, closes #92.

Created initial Evidence objects

---

src/main/java/duke/task/Investigation.java
src/main/java/duke/task/Medicine.java
src/main/java/duke/task/Plan.java

Created initial Plan, Medicine and Investigation Objects
Todo: toString methods, check on toResult method in Investigation Object
This closes #96, closes #95, closes #94.

Created initial Treatment objects

---

src/main/java/duke/gui/UiComponent.java
src/main/java/duke/gui/UiElement.java

All major UI elements in Dr. Duke may now extend from this abstract class. This makes for easier creation of UI elements.
closes #122

Create abstract class UiComponent

---

src/main/java/duke/task/GsonStorage.java
src/main/java/duke/task/PatientMap.java

The PatientMap object stores all the patients for Duke.
closes #128

Initial PatientMap object

---

src/main/java/duke/data/PatientMap.java

Modified stored hash map to observable map so that GUI can listen for changes.
closes #137

PatientMap: Change HashMap to ObservableMap

---

src/main/java/duke/data/Patient.java
src/test/java/GsonStorageTest.java

Convert Primitive int to object int. All invalid values are null.
Overloaded constructor, all new patients with switches should be called with the new constructor, invalid values represented with null.
closes #151

Patient: Convert primitive int to Object Integer

---

src/main/java/duke/data/DukeData.java
src/main/java/duke/data/DukeObject.java
src/main/java/duke/data/Evidence.java
src/main/java/duke/data/Impression.java
src/main/java/duke/data/Investigation.java
src/main/java/duke/data/Medicine.java
src/main/java/duke/data/Observation.java
src/main/java/duke/data/Patient.java
src/main/java/duke/data/PatientMap.java
src/main/java/duke/data/Plan.java
src/main/java/duke/data/Result.java
src/main/java/duke/data/Treatment.java
src/test/java/GsonStorageTest.java

We can now search the entire model of data for any particular search term. This is done by completing the toString methods

Complete toString methods and find methods

---

.travis.yml
README.md
build.gradle
gradle.properties

Resolve Coveralls bug

---

src/main/java/duke/command/CommandHelpers.java
src/main/java/duke/data/DukeData.java
src/main/java/duke/data/Impression.java
src/main/java/duke/data/Patient.java

Change null values to invalid values.
Change seperator in toString from \t to -

Null values and toString

---

src/main/java/duke/command/Commands.java
src/main/java/duke/command/PatientDischargeCommand.java
src/main/java/duke/command/PatientDischargeSpec.java

Patient discharge command

---

src/main/java/duke/command/Commands.java
src/main/java/duke/command/HomeNewCommand.java
src/main/java/duke/command/PatientNewCommand.java
src/main/java/duke/command/PatientNewSpec.java
src/main/java/duke/data/Patient.java

cleaned up null values in Patient class
added command for new impression
note impression currently cannot be displayed in the card as the Impression hash map is not observable
instead will print impression added in command window
WIP on conversion from HashMap to ObservableMap is added as comments
this closes #185

New impression

---

src/main/java/duke/command/Commands.java
src/main/java/duke/command/PatientFindCommand.java
src/main/java/duke/command/PatientFindSpec.java

Todo: Home context find command
this with #195 closes #191

PatientFindCommand: new find command in patient context

---

src/main/java/duke/command/Commands.java
src/main/java/duke/command/UpCommand.java
src/main/java/duke/command/UpSpec.java
src/main/java/duke/ui/CommandWindow.java
src/main/java/duke/ui/ImpressionCard.java
src/main/java/duke/ui/InputHistoryWindow.java
src/main/java/duke/ui/PatientCard.java
src/main/java/duke/ui/PatientWindow.java
src/main/java/duke/ui/UiContext.java

Create [up] command

---

src/main/java/duke/data/Impression.java
src/main/java/duke/data/PatientMap.java

Use transient ObservableMaps to make attributes and hashmaps observable.
closes #224

Impression: make all attributes observable

---

src/main/java/duke/ui/Context.java
src/main/java/duke/ui/EvidenceCard.java
src/main/java/duke/ui/ImpressionWindow.java
src/main/java/duke/ui/MainWindow.java
src/main/resources/view/ImpressionWindow.fxml

Impression window

---

src/main/java/duke/command/Commands.java
src/main/java/duke/command/HomeFindCommand.java
src/main/java/duke/command/HomeFindSpec.java
src/main/java/duke/command/PatientFindCommand.java
src/main/java/duke/data/PatientMap.java

Bug fix for loading impressions

Find command home

---

docs/UserGuide.adoc
src/main/java/duke/command/ArgCommand.java
src/main/java/duke/command/CommandHelpers.java
src/main/java/duke/command/DukeDataCommand.java
src/main/java/duke/command/HomeFindCommand.java
src/main/java/duke/command/HomeNewCommand.java
src/main/java/duke/command/ImpressionEditCommand.java
src/main/java/duke/command/ImpressionEditSpec.java
src/main/java/duke/command/ImpressionNewCommand.java
src/main/java/duke/command/PatientNewSpec.java
src/main/java/duke/data/DukeData.java
src/main/java/duke/data/DukeObject.java
src/main/java/duke/data/Evidence.java
src/main/java/duke/data/Impression.java
src/main/java/duke/data/Medicine.java
src/main/java/duke/data/Observation.java
src/main/java/duke/data/Plan.java
src/main/java/duke/data/RuntimeTypeAdapterFactory.java
src/main/java/duke/data/Treatment.java
src/main/java/duke/ui/PatientWindow.java
src/test/java/CommandTest.java
src/test/java/GsonStorageTest.java
src/test/java/mocks/DoctorCommand.java

Edit command for Impressions completed with some bugs
Closes #208

Add edit command for Impressions

---

src/main/java/duke/command/Commands.java
src/main/java/duke/command/impression/ImpressionFindCommand.java
src/main/java/duke/command/impression/ImpressionFindSpec.java

Create impression find command
note bug on loading from json when there are treatments or evidences

Impression find

---

src/main/java/duke/command/ArgCommand.java
src/main/java/duke/command/impression/ImpressionEditCommand.java
src/main/java/duke/command/impression/ImpressionNewCommand.java
src/main/java/duke/command/patient/PatientEditCommand.java
src/main/java/duke/data/Impression.java
src/main/java/duke/data/Patient.java
src/main/java/duke/ui/ImpressionWindow.java
src/main/java/duke/ui/InputHistoryWindow.java
src/main/java/duke/ui/PatientWindow.java
src/main/java/duke/ui/Strings.java
src/main/java/duke/ui/UiStrings.java
src/main/java/duke/ui/card/ImpressionCard.java
src/main/java/duke/ui/card/PatientCard.java
src/test/java/GsonStorageTest.java

Make changes throughout project to deal with null values.

Handle null values

---

docs/UserGuide.adoc

Revert some changes to the command structure.

Revert User Guide

---

src/main/java/duke/DukeCore.java
src/main/java/duke/command/ArgCommand.java
src/main/java/duke/command/impression/DukeDataCommand.java
src/main/java/duke/command/impression/ImpressionNewCommand.java
src/main/java/duke/data/DukeData.java
src/main/java/duke/data/Impression.java
src/main/java/duke/data/Medicine.java
src/main/java/duke/data/Patient.java
src/main/java/duke/data/PatientMap.java
src/main/java/duke/data/Treatment.java
src/main/java/duke/ui/UiManager.java
src/main/java/duke/ui/card/EvidenceCard.java
src/main/java/duke/ui/card/ImpressionCard.java
src/main/java/duke/ui/card/InvestigationCard.java
src/main/java/duke/ui/card/MedicineCard.java
src/main/java/duke/ui/card/ObservationCard.java
src/main/java/duke/ui/card/PatientCard.java
src/main/java/duke/ui/card/PlanCard.java
src/main/java/duke/ui/card/ResultCard.java
src/main/java/duke/ui/card/TreatmentCard.java
src/main/java/duke/ui/window/ImpressionWindow.java
src/test/java/CommandTest.java
src/test/java/GsonStorageTest.java
src/test/java/ImpressionCommandTest.java

CommandTest can be extended to create test files for tests in different contexts. Follow the example of ImpressionCommandTest to see how to do certain common tasks for testing commands.

Create command testing template

---

src/main/java/duke/command/ArgParser.java
src/main/java/duke/command/Parser.java
src/main/java/duke/command/home/HomeNewCommand.java
src/main/java/duke/command/home/HomeNewSpec.java
src/main/java/duke/command/impression/ImpressionNewCommand.java
src/main/java/duke/command/impression/ImpressionNewSpec.java
src/main/java/duke/command/patient/PatientNewCommand.java
src/main/java/duke/command/patient/PatientNewSpec.java
src/main/java/duke/data/Impression.java
src/test/java/GsonStorageTest.java
src/test/java/HomeCommandTest.java
src/test/java/ImpressionCommandTest.java
src/test/java/ParserTest.java
src/test/java/PatientCommandTest.java
src/test/java/mocks/DoctorCommand.java
src/test/java/mocks/TestCommands.java
src/test/java/mocks/ValidEmptyCommand.java
src/test/java/mocks/ValidEmptySpec.java

Updated parser to force argument to be supplied immediately after command name, but remove requirement for strings to be quoted, closes #260 
Also added several other test suites and removed redundant -name switches, closes #256 
UG updates coming soon

New parser rules

---

src/main/java/duke/command/home/HomeOpenSpec.java
src/main/java/duke/command/impression/ImpressionEditSpec.java
src/main/java/duke/command/patient/PatientOpenSpec.java
src/main/java/duke/command/patient/PatientUtils.java
src/test/java/tests/ImpressionCommandTest.java

Crucially, these tests provide a template for testing ObjCommands

Create ImpressionEdit command tests
